### ISSUE TITLE
Expose data in Preset

### ISSUE THREAD

**Issue by arein** [WalletConnect/rpc-proxy#57] opened 2022-11-29 19:58 UTC
Acceptance criteria:
+ Dashboard depicting the RPC usage exposed in preset (@chadyj can you advise?)

Prerequisites:
+ AWS Glue crawler setup in `data-lake` repository to create Athena tables / maintain Athena partitions.

**Comment by chadyj** [comment] 2022-12-08 13:31
@arein just gimme a table name and I'll set it up!

**Comment by arein** [comment] 2022-12-08 17:03
@tonicebrian you can duplicate the Crawler logic [here](https://github.com/WalletConnect/data-lake/blob/master/terraform/relay_metrics/main.tf#L5-L104).

You can then log into AWS and click "Run" on the Crawlers to have them to an initial run (otherwise they run once an hour i think). That should then set up the tables.

**Comment by chadyj** [comment] 2022-12-08 17:49
@tonicebrian Great to start with all the data if possible.
Method name, chain, volume.  
RPC provider (eg infura)
Are the requests volume batched? 
Also include the basics from other tables, such as projectid, project name, country, etc.

Later, this will be part of the customer metrics report:
- v2 usage
- RPC usage

**Comment by chadyj** [comment] 2022-12-19 07:14
This is looking great, and is almost complete.

A few things to finish:

- Add "project name" column, like in the other message tables. This is helpful to understand who is using the service

- Clarify or fix what "sender" is.  Now it is a bunch of IP's. Ideally we would get the "host" of the dapp.  So if uniswap was using web3modal with our RPC, the "hose" would be "uniswap.com"

<img width="810" alt="Screenshot 2022-12-19 at 08 11 58" src="https://user-images.githubusercontent.com/116099/208368215-81882b3e-d53e-41ee-bfb9-5f050908b247.png">


Here is the preset chart so far:
https://ecbd21cc.us2a.app.preset.io/superset/dashboard/11/?native_filters_key=Wf0hSZKNpo8OR8K531u4UU7Oe2hkOlmXSdWinaA_uDYU95l2fwgIvdopmW7ga5m2

![rpc-2022-12-19T07-14-28 792Z](https://user-images.githubusercontent.com/116099/208368578-0fa852b9-b3bb-49a5-abaa-5a0be0c685e0.jpg)

**Comment by chadyj** [comment] 2022-12-19 10:05
Thanks Toni. I'll await the response from Derek and Xav, but just wanted to menion one thing about Preset.

> write queries using joins in Preset

This is not supported in the UI or explorer view.
I think the preferred approach is to create a view at the DB level.

https://superset.apache.org/docs/frequently-asked-questions/

**Comment by tonicebrian** [comment] 2022-12-19 10:17
The problem is that views are not materialized in Athena so when your data grows Preset performance will degrade since every query involves a full scan of the data. There are 2 solutions to this problem:

- Materialize by hand in the data warehouse the tables you need. That would be the preferred approach if the combination of sources is small both in the number of tables and columns.
- Perform joins using the SQL Lab in Preset. That would be the preferred approach when you cannot predict which analysis will be of interest to Data Analysts or the combination of data sources creates a combinatorial explosion in the materialized table.

**Comment by chadyj** [comment] 2022-12-19 10:48
> Perform joins using the SQL Lab in Preset. 

This is a bummer, because the joy of Preset has been no-SQL, particularly for adhoc data exploration.

**Comment by arein** [comment] 2022-12-19 16:32
From my chat with Toni:
1) we will now use the view to unblock Chad now.
2) Toni will setup the data warehouse logic so we will have a better solution going forward

**Comment by chadyj** [comment] 2023-01-16 12:53
Are we ready to close this?

THere is a related issue here https://github.com/WalletConnect/data-lake/issues/46

And still the requirement mentioned above to show the RPC provider (eg infura, or pokt).

**Comment by tonicebrian** [comment] 2023-01-17 14:27
@chadyj yes we can close it

**Closed by tonicebrian** 2023-01-17 14:27 UTC
Labels: accepted

**Comment by chadyj** [comment] 2023-01-17 14:39
@tonicebrian how about this?

> And still the requirement mentioned above to show the RPC provider (eg infura, or pokt).

**Comment by tonicebrian** [comment] 2023-01-17 15:34
Hey @chadyj let's have a call tomorrow morning. I think this is ill defined somehow because from a data point of view we are done. If something is missing I need to have the full picture. I'll send invites.
